# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_workspace/20190930_test/WRA_NOCORE/V3/V3.srcs/sources_1/ip/FilterRam/FilterRam.xci
# IP: The module: 'FilterRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_workspace/20190930_test/WRA_NOCORE/V3/V3.srcs/sources_1/ip/FilterRam/FilterRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FilterRam'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/vivado_workspace/20190930_test/WRA_NOCORE/V3/V3.srcs/sources_1/ip/FilterRam/FilterRam.xci
# IP: The module: 'FilterRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_workspace/20190930_test/WRA_NOCORE/V3/V3.srcs/sources_1/ip/FilterRam/FilterRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FilterRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
