# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc.xdc

# IP: ip/blk_mem_gfgt_1/blk_mem_gfgt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gfgt || ORIG_REF_NAME==blk_mem_gfgt} -quiet] -quiet

# IP: ip/block_ram1/block_ram1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_ram1 || ORIG_REF_NAME==block_ram1} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet

# XDC: ip/block_ram1/block_ram1_ooc.xdc

# XDC: ip/clk_wiz_1/clk_wiz_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_1/clk_wiz_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_1/clk_wiz_1_ooc.xdc
