# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_workspace/20190923_sim_ok/WRA_NOCORE/V3/V3.srcs/sources_1/ip/mult_lut/mult_lut.xci
# IP: The module: 'mult_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_workspace/20190923_sim_ok/WRA_NOCORE/V3/V3.srcs/sources_1/ip/mult_lut/mult_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_lut'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/vivado_workspace/20190923_sim_ok/WRA_NOCORE/V3/V3.srcs/sources_1/ip/mult_lut/mult_lut.xci
# IP: The module: 'mult_lut' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_workspace/20190923_sim_ok/WRA_NOCORE/V3/V3.srcs/sources_1/ip/mult_lut/mult_lut_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_lut'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
