
set_property PACKAGE_PIN U13 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property PACKAGE_PIN K2 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]

set_property PACKAGE_PIN T14 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property PACKAGE_PIN P14 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property PACKAGE_PIN J14 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property PACKAGE_PIN T9 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property PACKAGE_PIN J18 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property PACKAGE_PIN J17 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property PACKAGE_PIN L18 [get_ports {seg_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[0]}]
set_property PACKAGE_PIN T11 [get_ports {seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[1]}]
set_property PACKAGE_PIN P15 [get_ports {seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[3]}]
set_property PACKAGE_PIN K16 [get_ports {seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[4]}]
set_property PACKAGE_PIN R10 [get_ports {seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[5]}]
set_property PACKAGE_PIN T10 [get_ports {seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_led[6]}]






set_property PACKAGE_PIN E3 [get_ports sys_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_in]
set_property PACKAGE_PIN C12 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN H17 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property PACKAGE_PIN K15 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property PACKAGE_PIN J13 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN N14 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property PACKAGE_PIN R18 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports led4]
set_property PACKAGE_PIN V17 [get_ports led5]
set_property IOSTANDARD LVCMOS33 [get_ports led5]
set_property PACKAGE_PIN U17 [get_ports led6]
set_property IOSTANDARD LVCMOS33 [get_ports led6]


set_property PACKAGE_PIN E17 [get_ports cmos_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk]
set_property PACKAGE_PIN H16 [get_ports cmos_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_scl]
set_property PACKAGE_PIN G13 [get_ports cmos_sda]
set_property PACKAGE_PIN F16 [get_ports cmos_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst_n]
set_property PACKAGE_PIN H14 [get_ports cmos_vsync]
set_property PACKAGE_PIN G16 [get_ports cmos_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_href]
set_property PACKAGE_PIN F13 [get_ports {cmos_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[0]}]
set_property PACKAGE_PIN D14 [get_ports {cmos_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[1]}]
set_property PACKAGE_PIN E16 [get_ports {cmos_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_d[2]}]
set_property PACKAGE_PIN G17 [get_ports {cmos_data[3]}]
set_property PACKAGE_PIN G18 [get_ports {cmos_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[4]}]
set_property PACKAGE_PIN E18 [get_ports {cmos_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[5]}]
set_property PACKAGE_PIN F18 [get_ports {cmos_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[6]}]
set_property PACKAGE_PIN D18 [get_ports {cmos_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_d[7]}]

#set_property PACKAGE_PIN E17 [get_ports cmos_pclk]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_pclk]
#set_property PACKAGE_PIN H16 [get_ports cmos_scl]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_scl]
#set_property PACKAGE_PIN G13 [get_ports cmos_sda]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_sda]
#set_property PACKAGE_PIN G4 [get_ports cmos_rst_n]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_rst_n]
#set_property PACKAGE_PIN H14 [get_ports cmos_vsync]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync]
#set_property PACKAGE_PIN G16 [get_ports cmos_href]
#set_property IOSTANDARD LVCMOS33 [get_ports cmos_href]
#set_property PACKAGE_PIN F13 [get_ports {cmos_data[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[0]}]
#set_property PACKAGE_PIN D14 [get_ports {cmos_data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[1]}]
#set_property PACKAGE_PIN E16 [get_ports {cmos_data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_d[2]}]
#set_property PACKAGE_PIN G17 [get_ports {cmos_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[3]}]
#set_property PACKAGE_PIN G18 [get_ports {cmos_data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[4]}]
#set_property PACKAGE_PIN E18 [get_ports {cmos_data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[5]}]
#set_property PACKAGE_PIN F18 [get_ports {cmos_data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[6]}]
#set_property PACKAGE_PIN D18 [get_ports {cmos_data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_d[7]}]







set_property PACKAGE_PIN C7 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN B12 [get_ports vga_vs]

set_property PACKAGE_PIN B11 [get_ports vga_hs]
set_property PACKAGE_PIN B4 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[3]}]

set_property PACKAGE_PIN A3 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN D7 [get_ports {vga_rgb[2]}]


set_property PACKAGE_PIN C6 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN A4 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos_sda]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos_pclk_IBUF]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cmos_pclk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gray1[0]} {gray1[1]} {gray1[2]} {gray1[3]} {gray1[4]} {gray1[5]} {gray1[6]} {gray1[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list frame4_flag]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets cmos_pclk_IBUF_BUFG]
